Makefile

Remove creation of ECR repo from Makefile, the repo is already created.
None
CI runs

chore: Remove ECR create repository from Makefile

---

dkam/Chart.yaml
infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml
onboarding-manager/values.yaml

Update DKAM/OM/TinkerAction chart versions. Fixes apt update for other agents  in installer.
Fixed Kernel update version to 6.8.0-52

Update DKAM/OM/TinkerActions chart versions

---

.github/workflows/sanity-tests.yml

Now repos are public, we can remove GOPRIVATE.
None
CI runs.

chore: Remove useless GOPRIVATE

---

.github/workflows/post-merge.yml
README.md

OpenSSF and License Badge

---

.github/workflows/auto-add-labels.yml
.github/workflows/auto-close.yml
.github/workflows/auto-update.yml
.github/workflows/pre-merge.yml
.github/workflows/sanity-tests.yml

Moving the permissions to be per Job.

Moving the permissions to be per Job

---

.github/workflows/post-merge.yml
.github/workflows/pre-merge.yml
.github/workflows/sanity-tests.yml

chore: sort zizmor findings

---

dkam/Chart.yaml
infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml

chore: Make Infra-Onboarding Release v1.30.0

---

dkam/Chart.yaml
infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml

dkam@1.27.1 
om@1.37.1
Fixes # 22464

Bump version to 1.30.1

---

apiv2/Chart.yaml
infra-core/Chart.yaml

Releases apiv2 appVersion 0.0.4

---

amt/Chart.yaml
amt/charts/mps/Chart.yaml
amt/charts/mps/templates/db.yaml
amt/charts/mps/templates/job.yaml
amt/charts/mps/templates/secret-job.yaml
amt/charts/rps/Chart.yaml
amt/charts/rps/templates/db-job.yaml
infra-external/Chart.yaml

Update security policy in DMT charts and update version of DMT and infra-external

Update security policy in DMT charts

---

amt/Chart.yaml
amt/charts/mps/Chart.yaml
amt/charts/mps/templates/db.yaml
amt/charts/mps/templates/secrets-cm.yaml
amt/charts/mps/values.yaml
amt/charts/rps/Chart.yaml
amt/charts/rps/templates/db-job.yaml
amt/charts/rps/values.yaml
amt/values.yaml
infra-external/Chart.yaml

Signed-off-by: Ihor Kyrychok <ihor.kyrychok@intel.com>

Add DB type param

---

apiv2/Chart.yaml
infra-core/Chart.yaml

Releases apiv2 appversion 0.2.1 and infra-core charts

---

dkam/Chart.yaml
infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml

PUA fix to reduce the startup time

PUA fix to reduce the startup time

---

.gitignore
apiv2/Chart.yaml
infra-core/Chart.yaml
inventory/Chart.yaml

chore: infra-core inventory/apiv2 release

---

apiv2/Chart.yaml
infra-core/Chart.yaml

Release apiv2 with changes at:
- https://github.com/open-edge-platform/infra-core/pull/237
Fixes regex pattern in Provider resource fields in apiv2.

Releases apiv2 appVersion v2.1.0

---

.gitignore
Makefile
amt/Chart.yaml
amt/charts/mps/Chart.yaml
amt/charts/mps/templates/secrets-cm.yaml
infra-external/Chart.yaml

fix:enable ssl with no-verify

---

.github/workflows/sanity-tests.yml

Updates sanity tests to run with apiv2 integration tests.

Updates sanity-tests to use apiv2

---

.github/workflows/sanity-tests.yml

Signed-off-by: Ihor Kyrychok <ihor.kyrychok@intel.com>

Temporary disable infra-external

---

dkam/Chart.yaml
dkam/values.yaml
infra-onboarding/Chart.yaml

fix: remove deprecated `legacyMode` flag

---

.github/workflows/sanity-tests.yml

Adds logs to be saved from pods in orch-infra in sanity-tests

---

amt/Chart.yaml
amt/charts/dm-manager/Chart.yaml
apiv2/Chart.yaml
infra-core/Chart.yaml
infra-external/Chart.yaml
inventory/Chart.yaml

chore: infra-core inventory/apiv2 and infra-external amt release

---

infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml

Bump OM to 1.37.2

---

infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml

Includes: https://github.com/open-edge-platform/infra-onboarding/pull/166

Update OM to v1.37.5 and release infra-onboarding

---

infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml

Bump onboarding manager to 1.37.6

---

amt/Chart.yaml
amt/charts/dm-manager/Chart.yaml
amt/charts/dm-manager/templates/deployment.yaml
amt/charts/dm-manager/values.yaml
infra-external/Chart.yaml

included OIDC configuration for RBAC
NO 3rd party dependencies.
tested with EMF deployment .

OIDC server URL changes

---

dkam/Chart.yaml
infra-config/Chart.yaml
infra-config/values.yaml
infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml

Bump OM, DKAM and infra-config version

---

amt/Chart.yaml
amt/charts/dm-manager/Chart.yaml
amt/charts/dm-manager/templates/_helpers.tpl
amt/charts/dm-manager/templates/configmap.yaml
amt/charts/dm-manager/templates/job.yaml
amt/charts/dm-manager/templates/secret.yaml
amt/charts/dm-manager/values.yaml
infra-external/Chart.yaml

Remove hard coded password

---

infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml

Bump OM version to 1.38.3

---

amt/Chart.yaml
amt/charts/dm-manager/Chart.yaml
infra-external/Chart.yaml

Remove validator in dm-manager gRPC service.
https://github.com/open-edge-platform/infra-external/pull/154

DM-manager release

---

amt/Chart.yaml
amt/charts/dm-manager/Chart.yaml
infra-external/Chart.yaml

Update DM-manager chart version to include fix for power status when indicator is in Unspecified state

fix: Update power status settings when indication is Unknown

---

infra-onboarding/Chart.yaml
tinkerbell/Chart.yaml
tinkerbell/templates/nginx.yaml

Enforce redeployment on chart version change

---

infra-onboarding/Chart.yaml
onboarding-manager/Chart.yaml

Installer script changes to build and install LMS from source - https://github.com/open-edge-platform/infra-onboarding/pull/238/files

OM release 1.38.5

---

infra-onboarding/Chart.yaml
pxe-server/Chart.yaml

Bump pxe-server version to 0.1.1

---

amt/Chart.yaml
amt/charts/dm-manager/Chart.yaml
amt/charts/mps/Chart.yaml
amt/charts/rps/Chart.yaml
infra-external/Chart.yaml

Update dm-manager version

---

amt/Chart.yaml
amt/charts/mps/Chart.yaml
amt/charts/mps/templates/secret-job.yaml
amt/charts/mps/templates/secrets-cm.yaml
infra-external/Chart.yaml

This PR migrates the kubectl bitnamilegacy image to alpine

Migrate kubectl bitnamilegacy to alpine

---

infra-core/Chart.yaml
inventory/Chart.yaml

Release inv 2.30.4

---

apiv2/Chart.yaml
infra-core/Chart.yaml
infra-onboarding/Chart.yaml
inventory/Chart.yaml
onboarding-manager/Chart.yaml
onboarding-manager/values.yaml

Bump OM, apiv2,inventory and tinker action version

---

.github/workflows/post-merge.yml

Update bootstrap action in post-merge
